### ISSUE TITLE
'SimpleAuth/SimpleAuth.h' file not found

### ISSUE THREAD

**Issue by daithiw44** [adamjmcgrath/react-native-simple-auth#19]
Hi,

Any help here would be appreciated I have followed the instructions and the podFile install successfully (see below). However 'SimpleAuth/SimpleAuth.h' file not found in SimpleAuthWrapper.m. Any ideas? Thanks..

---

_pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using CMDQueryStringSerialization (0.4.1)
Using ISO8601 (0.3.0)
Using NSData+Base64 (1.0.0)
Using ReactiveCocoa (2.5)
Using SimpleAuth (0.3.9)
Using cocoa-oauth (0.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 6 total
pods installed._

**Comment by ktoh** [comment]
You may need to configure xcode so that it can find the header file. 

Take a look at this writeup and see the section that starts with  "once you drag SimpleAuthWrapper.h and SimpleAuthWrapper.m` into your XCode project, you may need to tell the project where to find files referenced inside these headers..." 
https://github.com/adamjmcgrath/react-native-simple-auth/issues/14

**Comment by daithiw44** [comment]
Hi,
Thanks a lot , was simply I had the Pod directory referenced incorrectly.
