### ISSUE TITLE
Authorize error

### ISSUE THREAD

**Issue by parmarnishant** [adamjmcgrath/react-native-simple-auth#27]
![image](https://cloud.githubusercontent.com/assets/3091518/12001889/8cce4794-ab18-11e5-8295-26dd0718a96e.png)

**Comment by adamjmcgrath** [comment]
Hi, could you add the error log from XCode?

**Comment by parmarnishant** [comment]
Hi, I tried twitter and facebook. Getting this in both.
Response: (null)
Error:Error Domain=SimpleAuthErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x7f9d0bc9d680 {Error Domain=com.apple.accounts Code=6 "(null)"}}

**Comment by adamjmcgrath** [comment]
Ah, ok - this is expected behaviour. the Twitter and Facebook providers use iOS social framework. When you're not logged in to Facebook on the device, you get `Error Domain=com.apple.accounts Code=6`. To fix - go to settings on your device and log in to Facebook (https://support.apple.com/en-gb/HT202605)

If you want to prompt the user to login if they're not already logged in on their iphone, you can customise the error message or use the 'FacebookWeb' provider (which spawns a WebView with the Facebook login form) as a fallback, something like https://github.com/adamjmcgrath/react-native-simple-auth/issues/25#issuecomment-166947111

**Comment by parmarnishant** [comment]
great . Thank you for resolving this on time ..
