### ISSUE TITLE
What's a good companion package for basic email/password auth?

### ISSUE THREAD

**Issue by faceyspacey** [adamjmcgrath/react-native-simple-auth#34]
What is this package typically paired up with to offer both types of login?

**Comment by adamjmcgrath** [comment]
Not sure to be honest, this package is designed to authenticate your users against a social service and give you their access tokens. The complexity is in the various Oauth steps that have to be handled by SimpleAuth. The process of storing those credentials is outside the scope of the library. 

Since email/password authentication is more straightforward I would probably roll my own solution for this. Then the question would be how would I store the credentials, be they tokens from SimpleAuth or basic email/password auth - and for this I would probably use something like: https://github.com/oblador/react-native-keychain

Hope this answers your question
