### ISSUE TITLE
And if the user dont do the login

### ISSUE THREAD

**Issue by pedrohenriquerls** [adamjmcgrath/react-native-simple-auth#50]
There's some callback to know if the user just back from browser to the app after doing nothing, just using the android back button?
Is possible deal with this?

**Comment by adamjmcgrath** [comment]
I don't think the library deals with this very well, will leave this issue open for when I have time to think of a possible solution

**Comment by johncblandii** [comment]
Any progress on a solution here, @adamjmcgrath? I'm hitting a need for this tonight.

**Comment by xzilja** [comment]
@adamjmcgrath I think you can deal with this using react-native App state and checking when it comes from background, there you can check if it came from url like `accounts.googe.com...` or similar for other providers and expose some sort of event like `canceled`? Because in successful scenario user will be redirected to url scheme specified by them?

**Comment by adamjmcgrath** [comment]
This should be fixed by https://github.com/adamjmcgrath/react-native-simple-auth/pull/102
