### ISSUE TITLE
Youtube? 

### ISSUE THREAD

**Issue by code812** [adamjmcgrath/react-native-simple-auth#53]
Do you have any idea how to reconfigure the scope in google auth to incorporate youtube validation? Specifically, this end point: https://www.googleapis.com/auth/youtube.readonly'.

**Comment by code812** [comment]
Sorry, figured it out. For reference, to enable youtube:

```
const SCOPE = 'https://www.googleapis.com/auth/youtube.readonly email profile';
const AUTH = 'https://accounts.google.com/o/oauth2/v2/auth';
const TOKEN = 'https://www.googleapis.com/oauth2/v4/token';
const YT = 'https://www.googleapis.com/youtube/v3/channels?part=brandingSettings,contentDetails,contentOwnerDetails,id,localizations,snippet,statistics,topicDetails,status&mine=true';
// const GOOGLE = 'https://www.googleapis.com/oauth2/v2/userinfo';
const checkError = ifElse(
  has('error'),
  pipe(prop('error'), curry((e) => { throw new Error(e); })),
  identity,
);

const getUser = curry((request, credentials) => pipe(
  prop('access_token'),
  getHeaders,
  set(lensProp('headers'), __, {}),
  pipeP(
    partial(request, [YT]),
    invoker(0, 'json'),
    set(lensProp('user'), __, {}),
    set(lensProp('credentials'), credentials),
  ),
)(credentials));
```

I'd like to be able to receive data from both the youtube & userinfo end points, but I haven't quite figured that out.

**Comment by adamjmcgrath** [comment]
The OAuth scope option should be made configurable (and some other options like [prompt](https://developers.google.com/identity/protocols/OAuth2UserAgent#request-parameter-prompt)), then you could login with the extra scope and make subsequent requests to the YouTube API with the credentials you get back, eg.

```js
import { google } from 'react-native-simple-auth';

const url = 'https://www.googleapis.com/youtube/v3/channels?part=brandingSettings,contentDetails,contentOwnerDetails,id,localizations,snippet,statistics,topicDetails,status&mine=true';

google({
  appId: '123-123abc.apps.googleusercontent.com',
  callback: 'com.reactnativesimpleauthexample:/oauth2redirect',
  scope: 'https://www.googleapis.com/auth/youtube.readonly email profile',
}).then((info) => {
  return fetch(url, {
    headers: { Authorization: `Bearer ${info.credentials.token}` },
  });
}).then((resp) => {
  // YT response
});
```

At the moment, the library is more geared towards Authentication (identifying the user using an OAuth provider) rather than Authorization (getting permission from the user to access various resources of the OAuth provider). I would like to add more authorization features (like exposing a method to add the necessary OAuth headers to a request), but haven't got the need for them so not got round to doing it. Happy to accept PRs if anyone wants to take a look.
