### ISSUE TITLE
Facebook app rather than Safari

### ISSUE THREAD

**Issue by pcofilada** [adamjmcgrath/react-native-simple-auth#73]
Is it possible to open Facebook app rather than Safari when logging in?

**Comment by adamjmcgrath** [comment]
The library uses the [Linking API](https://facebook.github.io/react-native/docs/linking.html#linking) to launch the Facebook OAuth dialog and since the url has the `https` scheme it will open the default browser on your OS.

```
https://www.facebook.com/v2.8/dialog/oauth?
  client_id={app-id}
  &redirect_uri={redirect-uri}
```

You might be better off with the official React Native Facebook SDK to do that https://github.com/facebook/react-native-fbsdk

**Comment by pcofilada** [comment]
I see. But how about this one?

![img_3777](https://cloud.githubusercontent.com/assets/4263778/25095121/d3105386-23cc-11e7-856d-acb9fa679c75.PNG)

**Comment by adamjmcgrath** [comment]
No idea, happy to accept a PR if you figure it out
